# shell.executable("/bin/bash") shell.prefix("source $HOME/.bashrc; ")
import glob

configfile: "config/config.yaml"

workdir: config["wdir"]

SAMPLES, = glob_wildcards(config['data'] + "/{smp}_contigs.fasta")

#print(SAMPLES)
#print(config)

rule all:
    input:
        prodigal_fa_done = expand(
            config["rdir"] + "/gene_prediction/{smp}.gp.done", smp=SAMPLES),
        pfam_annotation_done = expand(
            config["rdir"] + "/pfam_annotation/{smp}.annotation.done", smp=SAMPLES),
        pfam_annotation_res_done = expand(
            config["rdir"] + "/pfam_annotation/{smp}.annot_res.done", smp=SAMPLES),
        combine_sammples_done = config["rdir"] + "/combine_samples/comb.done",
        mmseqs_clustering_done = config["rdir"] + "/mmseqs_clustering/clu.done",
        mmseqs_clustering_res_done = config["rdir"] + "/mmseqs_clustering/clu_res.done",
        spurious_shadow_done = config["rdir"] + "/spurious_shadow/spsh.done",
        cluster_fvalidation_done = config["rdir"] + "/functional_validation/fval.done",
        cluster_cvalidation_done = config["rdir"] + "/compositional_validation/cval.done",
        cluster_validation_done = config["rdir"] + "/validation/val.done",
        cluster_refinement_done = config["rdir"] + "/cluster_refinement/ref.done",
        cluster_classific_done = config["rdir"] + "/cluster_classification/class.done",
        cluster_categ_ref_done = config["rdir"] + "/cluster_categories/cat_ref.done",
        cluster_categ_db_done = config["rdir"] + "/cluster_category_DB/cat_db.done",
        cluster_categ_stats_done = config["rdir"] + "/cluster_category_stats/cat_stats.done",
        cluster_comm_done = config["rdir"] + "/cluster_communities/comm.done",
        cludb_res_done = config["rdir"] + "/clusterDB_results/cludb_res.done",
        report_done = config["rdir"] + "/report/workflow_report.html"

include: "rules/gene_prediction.smk"
include: "rules/pfam_annotation.smk"
include: "rules/pfam_annotation_results.smk"
include: "rules/combine_samples.smk"
include: "rules/mmseqs_clustering.smk"
include: "rules/mmseqs_clustering_results.smk"
include: "rules/spurious_shadow.smk"
include: "rules/cluster_pfam_annotation.smk"
include: "rules/cluster_functional_validation.smk"
include: "rules/cluster_compositional_validation.smk"
include: "rules/cluster_validation_results.smk"
include: "rules/cluster_refinement.smk"
include: "rules/cluster_classification.smk"
include: "rules/cluster_category_refinement.smk"
include: "rules/cluster_category_database.smk"
include: "rules/cluster_category_stats.smk"
include: "rules/cluster_communities.smk"
include: "rules/cluster_db_results.smk"
include: "rules/workflow_report.smk"
